/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as EmpleadoRouteImport } from './routes/empleado'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmpleadoEnrollRouteImport } from './routes/empleado.enroll'

const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpleadoRoute = EmpleadoRouteImport.update({
  id: '/empleado',
  path: '/empleado',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpleadoEnrollRoute = EmpleadoEnrollRouteImport.update({
  id: '/enroll',
  path: '/enroll',
  getParentRoute: () => EmpleadoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/empleado': typeof EmpleadoRouteWithChildren
  '/panel': typeof PanelRoute
  '/empleado/enroll': typeof EmpleadoEnrollRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/empleado': typeof EmpleadoRouteWithChildren
  '/panel': typeof PanelRoute
  '/empleado/enroll': typeof EmpleadoEnrollRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/empleado': typeof EmpleadoRouteWithChildren
  '/panel': typeof PanelRoute
  '/empleado/enroll': typeof EmpleadoEnrollRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/empleado' | '/panel' | '/empleado/enroll'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/empleado' | '/panel' | '/empleado/enroll'
  id: '__root__' | '/' | '/admin' | '/empleado' | '/panel' | '/empleado/enroll'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  EmpleadoRoute: typeof EmpleadoRouteWithChildren
  PanelRoute: typeof PanelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empleado': {
      id: '/empleado'
      path: '/empleado'
      fullPath: '/empleado'
      preLoaderRoute: typeof EmpleadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empleado/enroll': {
      id: '/empleado/enroll'
      path: '/enroll'
      fullPath: '/empleado/enroll'
      preLoaderRoute: typeof EmpleadoEnrollRouteImport
      parentRoute: typeof EmpleadoRoute
    }
  }
}

interface EmpleadoRouteChildren {
  EmpleadoEnrollRoute: typeof EmpleadoEnrollRoute
}

const EmpleadoRouteChildren: EmpleadoRouteChildren = {
  EmpleadoEnrollRoute: EmpleadoEnrollRoute,
}

const EmpleadoRouteWithChildren = EmpleadoRoute._addFileChildren(
  EmpleadoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  EmpleadoRoute: EmpleadoRouteWithChildren,
  PanelRoute: PanelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
