/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EmpleadoRouteImport } from './routes/empleado'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmpleadoDashboardRouteImport } from './routes/empleado.dashboard'

const EmpleadoRoute = EmpleadoRouteImport.update({
  id: '/empleado',
  path: '/empleado',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpleadoDashboardRoute = EmpleadoDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => EmpleadoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/empleado': typeof EmpleadoRouteWithChildren
  '/empleado/dashboard': typeof EmpleadoDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/empleado': typeof EmpleadoRouteWithChildren
  '/empleado/dashboard': typeof EmpleadoDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/empleado': typeof EmpleadoRouteWithChildren
  '/empleado/dashboard': typeof EmpleadoDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/empleado' | '/empleado/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/empleado' | '/empleado/dashboard'
  id: '__root__' | '/' | '/empleado' | '/empleado/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmpleadoRoute: typeof EmpleadoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/empleado': {
      id: '/empleado'
      path: '/empleado'
      fullPath: '/empleado'
      preLoaderRoute: typeof EmpleadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empleado/dashboard': {
      id: '/empleado/dashboard'
      path: '/dashboard'
      fullPath: '/empleado/dashboard'
      preLoaderRoute: typeof EmpleadoDashboardRouteImport
      parentRoute: typeof EmpleadoRoute
    }
  }
}

interface EmpleadoRouteChildren {
  EmpleadoDashboardRoute: typeof EmpleadoDashboardRoute
}

const EmpleadoRouteChildren: EmpleadoRouteChildren = {
  EmpleadoDashboardRoute: EmpleadoDashboardRoute,
}

const EmpleadoRouteWithChildren = EmpleadoRoute._addFileChildren(
  EmpleadoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmpleadoRoute: EmpleadoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
